//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Richard Crawshaw")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Richard Crawshaw")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("A Windows GUI project to provide UserControls for CBUS Op-Codes and their propert" +
    "ies.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.9.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.9.1")]
[assembly: System.Reflection.AssemblyProductAttribute("Cbus.Gladsheimr")]
[assembly: System.Reflection.AssemblyTitleAttribute("Cbus.Gladsheimr")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.9.1.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/RichardCrawshaw/Gladsheimr")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]

// Generated by the MSBuild WriteCodeFragment class.

